### ISSUE TITLE
Decimals of DRM and sDRM are registered incorrectly

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/godwoken_explorer#350]
`decimals` read from contracts are `9`, but `18` were registered along with them.

Before decimal is fixed
![image](https://user-images.githubusercontent.com/7271329/162577769-badeb578-bc78-47a6-905d-eea44213482d.png)

**Comment by zmcNotafraid** [comment]
Fixed

**Comment by Keith-CY** [comment]
Could we fill `decimals` automatically with a call to its contract?

**Comment by Keith-CY** [comment]
This issue is not fixed, the actual decimals is `9`, but `18` was registered instead, then the value of DRM and sDRM are parsed incorrectly

**Comment by Keith-CY** [comment]
Please refer to this issue in the PR or append the PR in this issue @zmcNotafraid

**Comment by zmcNotafraid** [comment]
If you don't fill decimal and supply,It will auto get from the contract
